apiVersion: v1
kind: Pod
metadata:
  name: k6-load-generator
spec:
  containers:
  - name: k6
    image: grafana/k6
    command: ["k6", "run", "/scripts/load-test.js"]
    volumeMounts:
    - name: k6-scripts
      mountPath: /scripts
  volumes:
  - name: k6-scripts
    configMap:
      name: k6-script
  restartPolicy: Never
