apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
  namespace: consistent-hashing
  labels:
    app.kubernetes.io/name: kvstore
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: consistent-hashing
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kvstore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kvstore
        app.kubernetes.io/component: storage
    spec:
      containers:
      - name: kvstore
        image: consistent-hashing/kvstore:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LISTEN_PORT
          value: "8080"
        - name: GATEWAY_ADDRESS
          value: "gateway-service.consistent-hashing.svc.cluster.local:8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: kvstore-service
  namespace: consistent-hashing
  labels:
    app.kubernetes.io/name: kvstore
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kvstore
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kvstore-hpa
  namespace: consistent-hashing
  labels:
    app.kubernetes.io/name: kvstore
    app.kubernetes.io/component: storage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kvstore
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60 