apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: container-registry
  labels:
    app.kubernetes.io/name: container-registry
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # K3s default storage class 