apiVersion: v1
kind: Service
metadata:
  name: registry-nodeport
  namespace: container-registry
  labels:
    app.kubernetes.io/name: container-registry
    app.kubernetes.io/component: registry-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: container-registry
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 32000  # Fixed port for easy access
    protocol: TCP 