apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
  labels:
    app.kubernetes.io/name: container-registry
    app.kubernetes.io/version: "2.8.3"
    app.kubernetes.io/component: registry 