# .github/workflows/rate-limiter.yml

name: Rate Limiter Build

on:
  push:
    branches: [main]
    paths:
      - 'rate_limiter/**'     # Only trigger if files in this folder change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./rate_limiter
          push: true
          platforms: linux/amd64,linux/arm64
          tags: quay.io/manishym/rate-limiter:latest
